[package]
name = "logo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.12.1"
regex = "1.7.0"
santiago = "*"
rand = "*"

[dev-dependencies]
assert_cmd = "*"
predicates = "*"
